In [1]:
import numpy as np
vector_row = np.array([1,2,3])

In [2]:
vector_row

array([1, 2, 3])

In [3]:
matrix = np.array([[1,2],[1,2],[1,2]])

In [4]:
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [5]:
matrix_obj = np.mat([[1,2],[1,2],[1,2]])

In [6]:
matrix_obj

matrix([[1, 2],
        [1, 2],
        [1, 2]])

In [7]:
from scipy import sparse

In [8]:
matrix2 = np.array([[0,0],[0,1],[3,0]])

In [9]:
matrix2_sparse = sparse.csr_matrix(matrix)

In [10]:
matrix2_sparse

<3x2 sparse matrix of type '<class 'numpy.int64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [11]:
print(matrix2_sparse)

  (0, 0)	1
  (0, 1)	2
  (1, 0)	1
  (1, 1)	2
  (2, 0)	1
  (2, 1)	2


In [12]:
vector_row[2]

3

## This is a demo